### ISSUE TITLE
using add/observable operators

### ISSUE THREAD

**Issue by ovangle** [Reactive-Extensions/RxJS#1067]
I'm wondering about the utility of the static methods in `add/observable`. I can't seem to get them to work as expected.

`main.js`
```
require('rxjs/add/observable/fromArray)';
var observable = require('rxjs/observable');

observable.Observable.fromArray([0,1,2,3]).subscribe(console.log);
```

Running this file via node gives 
```
TypeError: observable.Observable.fromArray is not a function
    at Object.<anonymous> (/Users/ovangle/WebstormProjects/center_stage/sandbox/main.js:4:28)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)
    at startup (node.js:141:18)
    at node.js:980:3
```

Am I missing something? The exports from `add/operators` work as expected, but none of the static functions in `add/observable` seem to work.

**Comment by ovangle** [comment]
Sorry, I seem to have lodged this issue with the wrong library.
