### ISSUE TITLE
TypeError: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by drkhannah** [Reactive-Extensions/RxJS#1076]
/Applications/IBM/MobileFirst-CLI/mobilefirst-cli/node_modules/rx-lite/rx.lite.js:75
    throw e;
          ^
working on IBM mobilefirst platform trying to use command mfp cordova run android and I get this error

TypeError: Cannot read property 'length' of null
    at ScreenManager.render (/Applications/IBM/MobileFirst-CLI/mobilefirst-cli/node_modules/mfp_cordova_cmds/node_modules/inquirer/lib/utils/screen-manager.js:64:52)
    at Prompt.render (/Applications/IBM/MobileFirst-CLI/mobilefirst-cli/node_modules/mfp_cordova_cmds/node_modules/inquirer/lib/prompts/list.js:103:15)
    at Prompt.onSubmit (/Applications/IBM/MobileFirst-CLI/mobilefirst-cli/node_modules/mfp_cordova_cmds/node_modules/inquirer/lib/prompts/list.js:116:8)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (/Applications/IBM/MobileFirst-CLI/mobilefirst-cli/node_modules/rx-lite/rx.lite.js:1535:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Applications/IBM/MobileFirst-CLI/mobilefirst-cli/node_modules/rx-lite/rx.lite.js:1469:31)
    at AnonymousObserver.tryCatcher (/Applications/IBM/MobileFirst-CLI/mobilefirst-cli/node_modules/rx-lite/rx.lite.js:63:31)
    at AutoDetachObserverPrototype.nextohbocxxg5415yfv:kmf_cordova hannade$

**Comment by jadbox** [comment]
I've seen this happen when you have code that uses Rx.Observable.fromArray(x) with a parameter that is null or not an array object. Hope that helps!

**Comment by mattpodwysocki** [comment]
@drkhannah I need to see some code in order to diagnose this.
