### ISSUE TITLE
publishLast undefined in Beta 7

### ISSUE THREAD

**Issue by jdfreder** [Reactive-Extensions/RxJS#1252]
From what I can tell, the following should work because `publishLast` was added in the Alpha.  Why is it not working?

http://jsbin.com/tujapaciwo/1/edit?js,console

**Comment by jdfreder** [comment]
Here is the error I see on the JS bin shared above:

```
"TypeError: Rx.Observable.defer(...).merge(...).filter(...).distinctUntilChanged(...).publishLast is not a function
    at getChannels (tujapaciwo.js:37:60)
    at tujapaciwo.js:42:19"
```
