### ISSUE TITLE
file missing in 4.1.0 release

### ISSUE THREAD

**Issue by jmfrancois** [Reactive-Extensions/RxJS#1322]
I have the following trace on a CLI:

```
Error: Cannot find module './dist/rx'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/jmfrancois/node_modules/.../inquirer/node_modules/rx/index.js:1:72)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416
```

cd that folder and list the content

```
$ ls
authors.txt        bower.json         code-of-conduct.md component.json     contributing.md    dist               index.js           package.json
$ ls dist
rx.aggregates.js  rx.binding.min.js rx.coincidence.js rx.sorting.js
$ more index.js
var Rx = require('./dist/rx');
require('./dist/rx.aggregates');
require('./dist/rx.async');
require('./dist/rx.backpressure');
require('./dist/rx.binding');
require('./dist/rx.coincidence');
require('./dist/rx.experimental');
require('./dist/rx.joinpatterns');
require('./dist/rx.sorting');
require('./dist/rx.virtualtime');
require('./dist/rx.testing');
require('./dist/rx.time');

module.exports = Rx;
```

So there is a missing file in the dist folder, you should have an index.js file.

This is the last release issue so it should be consider as a priority to fix.

Thanks

**Comment by jmfrancois** [comment]
I really don't know what happened but after a big cleanup everythings is working well.
I suspect an issue in NPM but ...
