### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by ORESoftware** [Reactive-Extensions/RxJS#1394]
saw this bug just now, I don't think it's in my code. I am using rx-lite version  "rx-lite": "^4.0.8",

```console

(node:5828) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: this.error is not a function
TypeError: this.error is not a function
    at Rx.internals.AbstractObserver.AbstractObserver.onError (/home/oleg/WebstormProjects/oresoftware/cmd-queue/node_modules/rx-lite/rx.lite.js:1612:14)
(node:5828) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at emitWarning (internal/process/promises.js:69:15)
    at emitPendingUnhandledRejections (internal/process/promises.js:86:11)
    at runMicrotasksCallback (internal/process/next_tick.js:61:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by paulpdaniels** [comment]
Can you post code? This is related to a `Promise` not having an error handler and rejecting.

**Comment by ORESoftware** [comment]
I don't remember where I got this, I think I overwrote the code in question, otherwise I would provide you with it.

> This is related to a Promise not having an error handler and rejecting.

probably, but it's RxJS that has the error as far as I can tell. None of my code had `this.error` in it, I can assure you that 1500%. Please look into your code base near the stacktrace and look for ` this.error`
