### ISSUE TITLE
 (SystemJS) XHR error (404 Not Found) loading http://localhost:1762/node_modules/rxjs/operators.js

### ISSUE THREAD

**Issue by jrmcdona** [Reactive-Extensions/RxJS#1531]
OS: Windows 10
"rxjs": "^5.4.2"

This seems to be more of an issue on my machine as nobody else seems to have the issue.

I ran "npm cache clear --force" and then did "npm install" but the issue is still not fixed.   I have one other proejct in our solution that uses 5.5.2 so  I thought there might be an npm cache conflict.  But didn't work.

I can clearly see there is no operators.js in the node_modules/rxjs folder.
```
Failed to load resource: the server responded with a status of 404 (Not Found)
(index):35 Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:1762/node_modules/rxjs/operators.js
	Error: XHR error (404 Not Found) loading http://localhost:1762/node_modules/rxjs/operators.js
	    at XMLHttpRequest.wrapFn [as __zone_symbol___onreadystatechange] (http://localhost:1762/node_modules/zone.js/dist/zone.js:1393:29) [<root>]
	Error loading http://localhost:1762/node_modules/rxjs/operators.js as "./operators" from http://localhost:1762/node_modules/rxjs/Rx.js
	    at XMLHttpRequest.wrapFn [as __zone_symbol___onreadystatechange] (http://localhost:1762/node_modules/zone.js/dist/zone.js:1393:29) [<root>]
	Error loading http://localhost:1762/node_modules/rxjs/operators.js as "./operators" from http://localhost:1762/node_modules/rxjs/Rx.js
(anonymous) @ (index):35
ZoneDelegate.invoke @ zone.js:365
Zone.run @ zone.js:125
(anonymous) @ zone.js:760
ZoneDelegate.invokeTask @ zone.js:398
Zone.runTask @ zone.js:165
drainMicroTaskQueue @ zone.js:593
ZoneTask.invoke @ zone.js:464
:1762/node_modules/rxjs/operators.js 
```

Thanks

**Comment by jrmcdona** [comment]
Moving this to the rxjs 5 github
