### ISSUE TITLE
flatMap/concatMap failure in 2.3.25

### ISSUE THREAD

**Issue by briancavalier** [Reactive-Extensions/RxJS#583]
I just updated most.js perf test deps and re-ran for node 0.12.  It looks like there may be a regression in `flatMap` and `concatMap` in Rx 2.3.25.

[Here's a link to one of the perf tests](https://github.com/cujojs/most/blob/master/test/perf/concatMap.js#L48) that seems to be failing after updating to Rx 2.3.25 (it ran to completion using Rx 2.3.24), and here's the stack trace I'm getting:

```
TypeError: undefined is not a function
    at FromArraySink.run (/Users/brian/Projects/cujojs/most/test/perf/node_modules/rx/dist/rx.js:2539:36)
    at FromArrayObservable.subscribeCore (/Users/brian/Projects/cujojs/most/test/perf/node_modules/rx/dist/rx.js:2517:19)
    at setDisposable (/Users/brian/Projects/cujojs/most/test/perf/node_modules/rx/dist/rx.js:2178:46)
    at FromArrayObservable.subscribe [as _subscribe] (/Users/brian/Projects/cujojs/most/test/perf/node_modules/rx/dist/rx.js:2190:9)
    at FromArrayObservable.Rx.Observable.observableProto.subscribe.observableProto.forEach (/Users/brian/Projects/cujojs/most/test/perf/node_modules/rx/dist/rx.js:2124:19)
    at subscribe (/Users/brian/Projects/cujojs/most/test/perf/node_modules/rx/dist/rx.js:3067:39)
    at AnonymousObserver._onCompleted (/Users/brian/Projects/cujojs/most/test/perf/node_modules/rx/dist/rx.js:3070:13)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (/Users/brian/Projects/cujojs/most/test/perf/node_modules/rx/dist/rx.js:1929:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/Users/brian/Projects/cujojs/most/test/perf/node_modules/rx/dist/rx.js:1866:14)
    at AutoDetachObserverPrototype.completed (/Users/brian/Projects/cujojs/most/test/perf/node_modules/rx/dist/rx.js:4604:23)
```

Please let me know if I'm doing something wrong in the test and I'll be happy to fix.

**Comment by mattpodwysocki** [comment]
@briancavalier it was a regression on `fromArray` that got in there, yet somehow my tests pass. Already fixed as part of another commit.

**Comment by briancavalier** [comment]
@mattpodwysocki Cool, thanks!

**Comment by briancavalier** [comment]
@mattpodwysocki was the fix for this released in 2.4.0?  I'm still seeing the same error after re-running locally with 2.4.0.

**Comment by mattpodwysocki** [comment]
@briancavalier sorry, realized it wasn't double checking for a scheduler for the second parameter.  It is fixed in 2.4.1

**Comment by briancavalier** [comment]
Thanks, @mattpodwysocki.  I'll update to 2.4.1.

**Comment by briancavalier** [comment]
Confirmed: 2.4.1 works correctly.  I'll post updated results soon.  Thanks again.
