### ISSUE TITLE
rx 2.4.2 on npm is missing index.js

### ISSUE THREAD

**Issue by chadxz** [Reactive-Extensions/RxJS#619]
rx 2.4.2 on npm is missing index.js

```
test $ npm i rx@2.4.1                                                          
npm WARN package.json test@1.0.0 No description
npm WARN package.json test@1.0.0 No repository field.
npm WARN package.json test@1.0.0 No README data
rx@2.4.1 node_modules/rx
test $ cd node_modules/rx                                                      
rx $ ls
authors.txt     dist/           logos/          src/
bower.json      index.js        package.json    travis.sh
component.json  license.txt     readme.md       ts/
rx $ cd ../../                                                                 
test $ npm i rx@2.4.2                                                          
npm WARN package.json test@1.0.0 No description
npm WARN package.json test@1.0.0 No repository field.
npm WARN package.json test@1.0.0 No README data
rx@2.4.2 node_modules/rx
test $ cd node_modules/rx
rx $ ls                                                                        
authors.txt     dist/           modules/        src/
bower.json      license.txt     package.json    travis.sh
component.json  logos/          readme.md       ts/
rx $                                                       
```

this is causing any package that relies on rx to fail with 

```
module.js:340
    throw err;
          ^
Error: Cannot find module 'rx'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    [...]
```

**Comment by davidbenhaim** [comment]
+1

**Comment by cgurnik** [comment]
+1

**Comment by cgurnik** [comment]
+1

**Comment by rwky** [comment]
:+1:

**Comment by cviebrock** [comment]
+1 :disappointed:

**Comment by rickywiens** [comment]
+1

**Comment by robinsharma** [comment]
+1

**Comment by tcooc** [comment]
+1

**Comment by alanmoo** [comment]
+1

**Comment by mattpodwysocki** [comment]
Version pulled

**Comment by chadxz** [comment]
thanks @mattpodwysocki :)

**Comment by mattpodwysocki** [comment]
That is the weirdest one ever since that seems to be a NPM issue, notme

**Comment by mattpodwysocki** [comment]
@chadxz like I said, something went wrong in the deploy since index.js should have been in there.  It's on disk as you can see and the npm ignore hasn't changed either.

**Comment by chadxz** [comment]
yeah i couldn't find anything wrong with the repo or anything, so it must have just been a botched npm publish or something? I dunno

**Comment by irideas** [comment]
+1

**Comment by bluedusk** [comment]
+1

**Comment by cpylua** [comment]
Seems the file `index.js` is missing again in 2.4.4...
