### ISSUE TITLE
On promise error, "Cannot call method 'subscribe' of undefined"

### ISSUE THREAD

**Issue by atombender** [Reactive-Extensions/RxJS#797]
Getting this error thrown as an uncaught exception:

```
TypeError: Cannot call method 'subscribe' of undefined
    at AnonymousObserver._onError (/tmp/20150701000730-id1vn/node_modules/rx/dist/rx.js:3053:32)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.error (/tmp/20150701000730-id1vn/node_modules/rx/dist/rx.js:1700:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onError (/tmp/20150701000730-id1vn/node_modules/rx/dist/rx.js:1634:14)
    at AnonymousObserver.tryCatcher (/tmp/20150701000730-id1vn/node_modules/rx/dist/rx.js:563:29)
    at AutoDetachObserverPrototype.error (/tmp/20150701000730-id1vn/node_modules/rx/dist/rx.js:5175:52)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onError (/tmp/20150701000730-id1vn/node_modules/rx/dist/rx.js:1634:14)
    at MergeObserver.onError (/tmp/20150701000730-id1vn/node_modules/rx/dist/rx.js:3297:18)
    at MergeObserver.tryCatcher (/tmp/20150701000730-id1vn/node_modules/rx/dist/rx.js:563:29)
    at AutoDetachObserverPrototype.error (/tmp/20150701000730-id1vn/node_modules/rx/dist/rx.js:5175:52)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onError (/tmp/20150701000730-id1vn/node_modules/rx/dist/rx.js:1634:14)
    at InnerObserver.onError (/tmp/20150701000730-id1vn/node_modules/rx/dist/rx.js:4709:59)
    at InnerObserver.tryCatcher (/tmp/20150701000730-id1vn/node_modules/rx/dist/rx.js:563:29)
    at AutoDetachObserverPrototype.error (/tmp/20150701000730-id1vn/node_modules/rx/dist/rx.js:5175:52)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onError (/tmp/20150701000730-id1vn/node_modules/rx/dist/rx.js:1634:14)
    at InnerObserver.onError (/tmp/20150701000730-id1vn/node_modules/rx/dist/rx.js:5050:59)
    at InnerObserver.tryCatcher (/tmp/20150701000730-id1vn/node_modules/rx/dist/rx.js:563:29)
```

Line 3053 is here:

```javascript
        var d = new SingleAssignmentDisposable();
        subscription.setDisposable(d);
        d.setDisposable(result.subscribe(o));
      }, function (x) { o.onCompleted(x); }));
```

My code is doing this, basically:

```javascript
.concatMap(events => Rx.Observable.defer(
   () => Promise.map(events, event => doStuff(event)))
.subscribe(...);
```

Here, `doStuff()` returns a promise, which rejects with an error. The error is never surfaced; instead, the above exception masks it.

This is using [2b37250](https://github.com/Reactive-Extensions/RxJS/commit/2b37250ef2646d240aa09b7b6d2649c84b6c817a) on master.

**Comment by xgrommx** [comment]
@atombender I think `Promise` doesn't have the method `map`

**Comment by atombender** [comment]
Using [Bluebird](https://github.com/petkaantonov/bluebird/blob/master/API.md), which does. Anyway, it works until there is an error.

**Comment by xgrommx** [comment]
@atombender Why you don't use `flatMap` and `forkJoin`:

``js
.flatMap(events => Rx.Observable.forkJoin.apply(Rx.Observable, events.map(event => Rx.Observable.defer(doStuff(event)))));
```

**Comment by atombender** [comment]
Because I'm more familiar with promises, but sure, that looks like it would do the trick. It won't solve this issue, though.

**Comment by paulpdaniels** [comment]
Do you have a small jsfiddle or equivalent replicating this behavior? I can look into if it is a bug.

**Comment by atombender** [comment]
Will try to set one up.

**Comment by mattpodwysocki** [comment]
@atombender awaiting a fiddle/jsbin showing this behavior, else this will be closed.

**Comment by atombender** [comment]
Unable to reproduce it in a test case. Closing until I can reproduce.

**Comment by atombender** [comment]
I suspect that it was caused by a `catch` not returning data, ie. my own damn fault.
