### ISSUE TITLE
`Rx.Observable.for` example doesn't work

### ISSUE THREAD

**Issue by bgrainger** [Reactive-Extensions/RxJS#874]
Copy [the example](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/for.md#example) for `Rx.Observable.for` into a new NodeJS project:

```
var Rx = require('rx');

/* Using Observables */
var array = [1, 2, 3];

var source = Rx.Observable.for(
    array,
    function (x) {
        return Rx.Observable.returnValue(x);
    });

var subscription = source.subscribe(
    function (x) {
        console.log('Next: ' + x);
    },
    function (err) {
        console.log('Error: ' + err);
    },
    function () {
        console.log('Completed');
    });
```

## Expected Output

```
// => Next: 1
// => Next: 2
// => Next: 3
// => Completed
```

## Actual Output

```
Error: TypeError: undefined is not a function
```

**Comment by bgrainger** [comment]
Adding `console.log(err.stack())` prints:

```
Error: TypeError: undefined is not a function
C:\Code\Projects\rx-test\node_modules\rx\dist\rx.js:71
    throw e;
          ^
TypeError: string is not a function
    at AnonymousObserver._onError (C:\Code\Projects\rx-test\index.js:18:25)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.error (C:\Code\Projects\rx-test\node_modules\rx\dist\rx.js:1699:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onError (C:\Code\Projects\rx-test\node_modules\rx\dist\rx.js:1635:14)
    at AnonymousObserver.tryCatcher (C:\Code\Projects\rx-test\node_modules\rx\dist\rx.js:59:29)
    at AutoDetachObserverPrototype.error (C:\Code\Projects\rx-test\node_modules\rx\dist\rx.js:5222:52)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onError (C:\Code\Projects\rx-test\node_modules\rx\dist\rx.js:1635:14)
    at C:\Code\Projects\rx-test\node_modules\rx\dist\rx.js:2049:50
    at invokeRecImmediate (C:\Code\Projects\rx-test\node_modules\rx\dist\rx.js:942:7)
    at Scheduler.scheduleNow [as _schedule] (C:\Code\Projects\rx-test\node_modules\rx\dist\rx.js:1136:50)
    at Scheduler.Rx.Scheduler.schedulerProto.scheduleWithState (C:\Code\Projects\rx-test\node_modules\rx\dist\rx.js:875:19)
```

**Comment by xgrommx** [comment]
`for` is an experimental method and contains only in full rx version like `rx.all.js`, `rx.all.compat.js` or `rx.experimental.js`

**Comment by bgrainger** [comment]
Run `npm install rx@~2.5.0` and the program works as expected (with rx 2.5.3). Run `npm install rx@3.0.0` and the error reproduces as shown above. So it appears that this was a breaking change introduced in RxJS 3.0, possibly inadvertently?

**Comment by bgrainger** [comment]
The issue is that the example code uses `returnValue`, which was [deprecated in 3.0.0](https://github.com/Reactive-Extensions/RxJS/releases/tag/v3.0.0).
