### ISSUE TITLE
Rx.Observable.buffer does now work with Rx.Observable.just() as the opening

### ISSUE THREAD

**Issue by kyp0717** [Reactive-Extensions/RxJS#906]
Hi,
I am testing/learning the Rx.Observable.buffer and not able to get this to work.  The code is as follow:

------ CODE ---------------------
var source = Rx.Observable.of(1,2,3,4,5,6,7,8,9,0)

var sbuf = source.buffer(
  // opening observable element
  Rx.observable.just(4),
  // closing function
  () => {return source.filter( x=> {return x===7})}
  )

var sub = sbuf.subscribe( x => console.log(x))

------ERROR MESSAGE --------

/home/kyp0717/repos/git-repos/ibNodeTest/test3.js:25
_rx2['default'].observable.just(4),
                          ^
TypeError: Cannot read property 'just' of undefined
    at Object.<anonymous> (/home/kyp0717/repos/git-repos/ibNodeTest/test3.js:15:16)
    at Module._compile (module.js:460:26)
    at normalLoader (/usr/lib/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:199:5)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/lib/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:216:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at Object.<anonymous> (/usr/lib/node_modules/babel/lib/_babel-node.js:144:25)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

**Comment by kyp0717** [comment]
Sorry.  I found the error.  Observable was not capitalized with in the code.
